# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(269, 350)
        Calculator.setMinimumSize(QtCore.QSize(2, 0))
        Calculator.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_1 = QtWidgets.QPushButton(Calculator)
        self.bt_1.setGeometry(QtCore.QRect(0, 50, 90, 60))
        self.bt_1.setMinimumSize(QtCore.QSize(90, 60))
        self.bt_1.setMaximumSize(QtCore.QSize(90, 60))
        self.bt_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_1.setStyleSheet("font: 20pt \"Agency FB\";\n"
"font: 24pt \"仿宋\";")
        self.bt_1.setIconSize(QtCore.QSize(16, 19))
        self.bt_1.setAutoRepeatDelay(300)
        self.bt_1.setObjectName("bt_1")
        self.textEdit = QtWidgets.QTextEdit(Calculator)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 271, 51))
        self.textEdit.setMouseTracking(False)
        self.textEdit.setTabletTracking(True)
        self.textEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEdit.setAutoFillBackground(False)
        self.textEdit.setObjectName("textEdit")
        self.bt_2 = QtWidgets.QPushButton(Calculator)
        self.bt_2.setGeometry(QtCore.QRect(90, 50, 90, 60))
        self.bt_2.setMinimumSize(QtCore.QSize(90, 60))
        self.bt_2.setMaximumSize(QtCore.QSize(90, 60))
        self.bt_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_2.setStyleSheet("font: 20pt \"Agency FB\";\n"
"font: 24pt \"仿宋\";")
        self.bt_2.setIconSize(QtCore.QSize(16, 19))
        self.bt_2.setAutoRepeatDelay(300)
        self.bt_2.setObjectName("bt_2")
        self.bt_3 = QtWidgets.QPushButton(Calculator)
        self.bt_3.setGeometry(QtCore.QRect(180, 50, 90, 60))
        self.bt_3.setMinimumSize(QtCore.QSize(90, 60))
        self.bt_3.setMaximumSize(QtCore.QSize(90, 60))
        self.bt_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_3.setStyleSheet("font: 20pt \"Agency FB\";\n"
"font: 24pt \"仿宋\";")
        self.bt_3.setIconSize(QtCore.QSize(16, 19))
        self.bt_3.setAutoRepeatDelay(300)
        self.bt_3.setObjectName("bt_3")
        self.bt_5 = QtWidgets.QPushButton(Calculator)
        self.bt_5.setGeometry(QtCore.QRect(90, 110, 90, 60))
        self.bt_5.setMinimumSize(QtCore.QSize(90, 60))
        self.bt_5.setMaximumSize(QtCore.QSize(90, 60))
        self.bt_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_5.setStyleSheet("font: 20pt \"Agency FB\";\n"
"font: 24pt \"仿宋\";")
        self.bt_5.setIconSize(QtCore.QSize(16, 19))
        self.bt_5.setAutoRepeatDelay(300)
        self.bt_5.setObjectName("bt_5")
        self.bt_6 = QtWidgets.QPushButton(Calculator)
        self.bt_6.setGeometry(QtCore.QRect(180, 110, 90, 60))
        self.bt_6.setMinimumSize(QtCore.QSize(90, 60))
        self.bt_6.setMaximumSize(QtCore.QSize(90, 60))
        self.bt_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_6.setStyleSheet("font: 20pt \"Agency FB\";\n"
"font: 24pt \"仿宋\";")
        self.bt_6.setIconSize(QtCore.QSize(16, 19))
        self.bt_6.setAutoRepeatDelay(300)
        self.bt_6.setObjectName("bt_6")
        self.bt_4 = QtWidgets.QPushButton(Calculator)
        self.bt_4.setGeometry(QtCore.QRect(0, 110, 90, 60))
        self.bt_4.setMinimumSize(QtCore.QSize(90, 60))
        self.bt_4.setMaximumSize(QtCore.QSize(90, 60))
        self.bt_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_4.setStyleSheet("font: 20pt \"Agency FB\";\n"
"font: 24pt \"仿宋\";")
        self.bt_4.setIconSize(QtCore.QSize(16, 19))
        self.bt_4.setAutoRepeatDelay(300)
        self.bt_4.setObjectName("bt_4")
        self.bt_8 = QtWidgets.QPushButton(Calculator)
        self.bt_8.setGeometry(QtCore.QRect(90, 170, 90, 60))
        self.bt_8.setMinimumSize(QtCore.QSize(90, 60))
        self.bt_8.setMaximumSize(QtCore.QSize(90, 60))
        self.bt_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_8.setStyleSheet("font: 20pt \"Agency FB\";\n"
"font: 24pt \"仿宋\";")
        self.bt_8.setIconSize(QtCore.QSize(16, 19))
        self.bt_8.setAutoRepeatDelay(300)
        self.bt_8.setObjectName("bt_8")
        self.bt_9 = QtWidgets.QPushButton(Calculator)
        self.bt_9.setGeometry(QtCore.QRect(180, 170, 90, 60))
        self.bt_9.setMinimumSize(QtCore.QSize(90, 60))
        self.bt_9.setMaximumSize(QtCore.QSize(90, 60))
        self.bt_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_9.setStyleSheet("font: 20pt \"Agency FB\";\n"
"font: 24pt \"仿宋\";")
        self.bt_9.setIconSize(QtCore.QSize(16, 19))
        self.bt_9.setAutoRepeatDelay(300)
        self.bt_9.setObjectName("bt_9")
        self.bt_7 = QtWidgets.QPushButton(Calculator)
        self.bt_7.setGeometry(QtCore.QRect(0, 170, 90, 60))
        self.bt_7.setMinimumSize(QtCore.QSize(90, 60))
        self.bt_7.setMaximumSize(QtCore.QSize(90, 60))
        self.bt_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_7.setStyleSheet("font: 20pt \"Agency FB\";\n"
"font: 24pt \"仿宋\";")
        self.bt_7.setIconSize(QtCore.QSize(16, 19))
        self.bt_7.setAutoRepeatDelay(300)
        self.bt_7.setObjectName("bt_7")
        self.bt_sub = QtWidgets.QPushButton(Calculator)
        self.bt_sub.setGeometry(QtCore.QRect(90, 230, 90, 60))
        self.bt_sub.setMinimumSize(QtCore.QSize(90, 60))
        self.bt_sub.setMaximumSize(QtCore.QSize(90, 60))
        self.bt_sub.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_sub.setStyleSheet("font: 20pt \"Agency FB\";\n"
"font: 24pt \"仿宋\";")
        self.bt_sub.setIconSize(QtCore.QSize(16, 19))
        self.bt_sub.setAutoRepeatDelay(300)
        self.bt_sub.setObjectName("bt_sub")
        self.bt_mu = QtWidgets.QPushButton(Calculator)
        self.bt_mu.setGeometry(QtCore.QRect(180, 230, 90, 60))
        self.bt_mu.setMinimumSize(QtCore.QSize(90, 60))
        self.bt_mu.setMaximumSize(QtCore.QSize(90, 60))
        self.bt_mu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_mu.setStyleSheet("font: 20pt \"Agency FB\";\n"
"font: 24pt \"仿宋\";")
        self.bt_mu.setIconSize(QtCore.QSize(16, 19))
        self.bt_mu.setAutoRepeatDelay(300)
        self.bt_mu.setObjectName("bt_mu")
        self.bt_add = QtWidgets.QPushButton(Calculator)
        self.bt_add.setGeometry(QtCore.QRect(0, 230, 90, 60))
        self.bt_add.setMinimumSize(QtCore.QSize(90, 60))
        self.bt_add.setMaximumSize(QtCore.QSize(90, 60))
        self.bt_add.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_add.setStyleSheet("font: 20pt \"Agency FB\";\n"
"font: 24pt \"仿宋\";")
        self.bt_add.setIconSize(QtCore.QSize(16, 19))
        self.bt_add.setAutoRepeatDelay(300)
        self.bt_add.setObjectName("bt_add")
        self.bt_div = QtWidgets.QPushButton(Calculator)
        self.bt_div.setGeometry(QtCore.QRect(180, 290, 90, 60))
        self.bt_div.setMinimumSize(QtCore.QSize(90, 60))
        self.bt_div.setMaximumSize(QtCore.QSize(90, 60))
        self.bt_div.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_div.setStyleSheet("font: 20pt \"Agency FB\";\n"
"font: 24pt \"仿宋\";")
        self.bt_div.setIconSize(QtCore.QSize(16, 19))
        self.bt_div.setAutoRepeatDelay(300)
        self.bt_div.setObjectName("bt_div")
        self.bt_equ = QtWidgets.QPushButton(Calculator)
        self.bt_equ.setGeometry(QtCore.QRect(0, 290, 181, 61))
        self.bt_equ.setStyleSheet("font: 20pt \"Agency FB\";\n"
"font: 24pt \"仿宋\";")
        self.bt_equ.setObjectName("bt_equ")

        self.retranslateUi(Calculator)
        self.bt_1.clicked.connect(Calculator.but_1)
        self.bt_2.clicked.connect(Calculator.but_2)
        self.bt_3.clicked.connect(Calculator.but_3)
        self.bt_4.clicked.connect(Calculator.but_4)
        self.bt_5.clicked.connect(Calculator.but_5)
        self.bt_6.clicked.connect(Calculator.but_6)
        self.bt_7.clicked.connect(Calculator.but_7)
        self.bt_8.clicked.connect(Calculator.but_8)
        self.bt_9.clicked.connect(Calculator.but_9)
        self.bt_add.clicked.connect(Calculator.but_add)
        self.bt_sub.clicked.connect(Calculator.but_sub)
        self.bt_mu.clicked.connect(Calculator.but_mu)
        self.bt_div.clicked.connect(Calculator.but_div)
        self.bt_equ.clicked.connect(Calculator.but_equ)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Form"))
        self.bt_1.setText(_translate("Calculator", "1"))
        self.textEdit.setHtml(_translate("Calculator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:600;\">0</span></p></body></html>"))
        self.bt_2.setText(_translate("Calculator", "2"))
        self.bt_3.setText(_translate("Calculator", "3"))
        self.bt_5.setText(_translate("Calculator", "5"))
        self.bt_6.setText(_translate("Calculator", "6"))
        self.bt_4.setText(_translate("Calculator", "4"))
        self.bt_8.setText(_translate("Calculator", "8"))
        self.bt_9.setText(_translate("Calculator", "9"))
        self.bt_7.setText(_translate("Calculator", "7"))
        self.bt_sub.setText(_translate("Calculator", "-"))
        self.bt_mu.setText(_translate("Calculator", "*"))
        self.bt_add.setText(_translate("Calculator", "+"))
        self.bt_div.setText(_translate("Calculator", "/"))
        self.bt_equ.setText(_translate("Calculator", "="))

